version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 22
        commands:
            - echo Installed Node 22
    pre_build:
        commands:
            - echo Installing NPM dependencies
            - npm install
    build:
        commands:
            - echo [`date`] Starting build...
            - npm run build

artifacts:
    files:
        - '**/*'
    discard-paths: no
    base-directory: out
